# Generated by Django 4.2.9 on 2025-12-09 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('company_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
